repo: openworm/org.openworm.website
shortDescription: "OpenWorm Website"
contributor-guide: "http://docs.openworm.org/community/#contribution-best-practices"
coordinator: stephen@openworm.org
gitter: "http://gitter.im/openworm/OpenWorm"
keywords: 
  - website
languages:
  - html5
members:
  - giovanni@openworm.org
  - matteo@openworm.org
parent:
  - openworm/OpenWorm
